In [1]:
import numpy as np

In [15]:
inputarray = np.array ([
    [1,2,3],
    [4,5,6]
])
inputarray

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
inputarray[1][1]

np.int64(5)

In [17]:
inputarray[0][1:]

array([2, 3])

In [18]:
arr = np.array([1200,34,2,62,2])
np.sort(arr)

array([   2,    2,   34,   62, 1200])