In [2]:
import numpy as np

In [4]:
inputArray = np.array ([
    [1,2,3],
    [4,5,6]
])

inputArray

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
inputArray.shape

(2, 3)

In [14]:
inputArray[0][1]

np.int64(2)

In [16]:
inputArray[0][1:]

array([2, 3])

In [18]:
np.zeros (2)

array([0., 0.])

In [20]:
np.ones (3)

array([1., 1., 1.])

### Sorting the array

In [23]:
arr = np.array([2,1,5,3,7,4,5,8])

In [25]:
np.sort (arr)

array([1, 2, 3, 4, 5, 5, 7, 8])

### Concat the array

In [28]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [30]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

### Reshape the array

In [35]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]
